"""empty message

Revision ID: 2f2de8692183
Revises:
Create Date: 2020-04-22 16:22:23.330784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f2de8692183"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("phone_number", sa.String(length=10), nullable=False),
        sa.Column("accident", sa.String(length=80), nullable=False),
        sa.Column("cause", sa.String(length=80), nullable=False),
        sa.Column("injury", sa.String(length=80), nullable=False),
        sa.Column("viable", sa.Boolean(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cases")
    # ### end Alembic commands ###
